"""Drop class_name column from classes table

Revision ID: 002_drop_class_name
Revises: 001_add_class_name
Create Date: 2025-09-17 21:50:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_drop_class_name'
down_revision = '001_add_class_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'class_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('class_name', sa.String(length=160), nullable=False))
    # ### end Alembic commands ###

