"""Add lecturer_id to attendance_sessions

Revision ID: 78d67cfab03e
Revises: 003_add_class_name_back
Create Date: 2025-09-18 04:30:17.374036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d67cfab03e'
down_revision = '003_add_class_name_back'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_attendance_sessions_lecturer_id', 'users', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_sessions_lecturer_id', type_='foreignkey')
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###
