"""Add last_login_at and avatar_url to users

Revision ID: e7ab814c660a
Revises: 78d67cfab03e
Create Date: 2025-09-18 06:10:10.093120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ab814c660a'
down_revision = '78d67cfab03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=False))
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
